services:
  mysql:
    image: mysql:8.0
    container_name: library-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5

  user-api:
    build: ./user-api
    container_name: user-api
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/user_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8081:8081"

  book-api:
    build: ./book-api
    container_name: book-api
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/library_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234

  loan-api:
    build: ./loan-api
    container_name: loan-api
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      user-api:
        condition: service_started
      book-api:
        condition: service_started
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/loan_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234

      USER_SERVICE_BASE_URL: http://user-api:8081
      BOOK_SERVICE_BASE_URL: http://book-api:8080

  gateway-api:
    build: ./gateway-api
    container_name: gateway-api
    restart: always
    depends_on:
      user-api:
        condition: service_started
      book-api:
        condition: service_started
      loan-api:
        condition: service_started
    ports:
      - "9000:9000"
    environment:
      USER_API_URL: http://user-api:8081
      BOOK_API_URL: http://book-api:8080
      LOAN_API_URL: http://loan-api:8082

volumes:
  mysql_data:
